[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[start]
cmd = "gunicorn src.app:app --host 0.0.0.0 --port $PORT"