services:
  - type: web
    name: sistema-clickup-contaazul
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        sync: false
